#! /usr/bin/env python
import rospy
import roslib
import actionlib

import sys

from mas_cob_move_base_action.msg import MoveBaseSafeAction, MoveBaseSafeGoal

if __name__ == '__main__':
    rospy.init_node('move_base_client_test')
    client = actionlib.SimpleActionClient('/mdr_actions/move_base_server', MoveBaseSafeAction)
    client.wait_for_server()
    goal = MoveBaseSafeGoal()
    goal.arm_safe_position = 'folded'
    if len(sys.argv) == 2:  # one argument was received : ok proceed
        try:
            goal.destination_location = str(sys.argv[2])
            timeout = 15.0
            rospy.loginfo('Sending action lib goal to move_base_server, destination: ' +
                          goal.destination_location)
            client.send_goal(goal)
            client.wait_for_result(rospy.Duration.from_sec(int(timeout)))
            print client.get_result()
        except:
            pass
    else:
        rospy.logerr('The arguments were not received in the proper format!')
        rospy.loginfo('usage: move_base DESTINATION')
