#!/usr/bin/env python
import rospy

from mas_cob_gripper_controller.gripper_controller import GripperController

if __name__ == '__main__':
    rospy.init_node('mas_cob_gripper_controller')
    try:
        GripperController()
    except rospy.ROSInterruptException:
        pass
